linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - nolintlint

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  importas:
    no-extra-aliases: true
    alias:
      - pkg: github.com/cosmos/cosmos-sdk/crypto/codec
        alias: cryptocodec
      - pkg: github.com/cosmos/cosmos-sdk/crypto/types
        alias: cryptotypes
      - pkg: github.com/cosmos/cosmos-sdk/x/slashing/types
        alias: slashingtypes
      - pkg: github.com/cometbft/cometbft/types
        alias: cbft
      - pkg: github.com/cometbft/cometbft/config
        alias: cbftconfig
      - pkg: github.com/cometbft/cometbft/crypto
        alias: cbftcrypto
      - pkg: github.com/cometbft/cometbft/crypto/ed25519
        alias: cbftcryptoed25519
      - pkg: github.com/cometbft/cometbft/crypto/encoding
        alias: cbftcryptoencoding
      - pkg: github.com/tendermint/go-amino
        alias: amino
      - pkg: github.com/cometbft/cometbft/libs/bytes
        alias: cbftbytes
      - pkg: github.com/cometbft/cometbft/libs/json
        alias: cbftjson
      - pkg: github.com/cometbft/cometbft/libs/log
        alias: cbftlog
      - pkg: github.com/cometbft/cometbft/libs/net
        alias: cbftnet
      - pkg: github.com/cometbft/cometbft/libs/os
        alias: cbftos
      - pkg: github.com/cometbft/cometbft/libs/rand
        alias: cbftrand
      - pkg: github.com/cometbft/cometbft/libs/service
        alias: cbftservice
      - pkg: github.com/cometbft/cometbft/p2p/conn
        alias: cbftp2pconn
      - pkg: github.com/cometbft/cometbft/privval
        alias: cbftprivval
      - pkg: github.com/cometbft/cometbft/proto/tendermint/types
        alias: cbftproto
      - pkg: github.com/cometbft/cometbft/proto/tendermint/crypto
        alias: cbftprotocrypto
      - pkg: github.com/cometbft/cometbft/proto/tendermint/privval
        alias: cbftprotoprivval
      - pkg: github.com/cometbft/cometbft/rpc/client
        alias: cbftrpcclient
      - pkg: github.com/cometbft/cometbft/rpc/client/http
        alias: cbftrpchttp
      - pkg: github.com/cometbft/cometbft/rpc/jsonrpc/client
        alias: cbftrpcjsonclient
      - pkg: github.com/cometbft/cometbft/rpc/jsonrpc/types
        alias: cbftrpcjsontypes
      - pkg: github.com/cometbft/cometbft/rpc/core/types
        alias: cbftrpctypes
      - pkg: github.com/grpc-ecosystem/go-grpc-middleware/retry
        alias: grpcretry
      - pkg : github.com/kraken-hpc/go-fork
        alias: fork
      - pkg: github.com/armon/go-metrics/prometheus
        alias: gmprometheus
      - pkg: github.com/mitchellh/go-homedir
        alias: homedir
      - pkg: gitlab.com/unit410/threshold-ed25519/pkg
        alias: tsed25519
      - pkg: github.com/Jille/raft-grpc-transport
        alias: raftgrpctransport
      - pkg: github.com/hashicorp/raft-boltdb/v2
        alias: boltdb

  maligned:
    suggest-new: true
  govet:
    misspell:
      locale: US
