linters:
  enable:
    - bodyclose
    - dogsled
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - nolintlint

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  importas:
    no-extra-aliases: true
    alias:
      - pkg: github.com/cosmos/cosmos-sdk/crypto/codec
        alias: cryptocodec
      - pkg: github.com/cosmos/cosmos-sdk/crypto/types
        alias: cryptotypes
      - pkg: github.com/cosmos/cosmos-sdk/x/slashing/types
        alias: slashingtypes
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/types
        alias: comet
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/config
        alias: cometconfig
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/crypto
        alias: cometcrypto
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/crypto/ed25519
        alias: cometcryptoed25519
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/crypto/bn254
        alias: cometcryptobn254
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/crypto/encoding
        alias: cometcryptoencoding
      - pkg: github.com/tendermint/go-amino
        alias: amino
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/libs/bytes
        alias: cometbytes
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/libs/json
        alias: cometjson
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/libs/net
        alias: cometnet
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/p2p/conn
        alias: cometp2pconn
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/privval
        alias: cometprivval
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/proto/types
        alias: cometproto
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/proto/crypto
        alias: cometprotocrypto
      - pkg: github.com/strangelove-ventures/horcrux/v3/comet/proto/privval
        alias: cometprotoprivval
      - pkg: github.com/ecies/go/v2
        alias: ecies
      - pkg: github.com/grpc-ecosystem/go-grpc-middleware/retry
        alias: grpcretry
      - pkg : github.com/kraken-hpc/go-fork
        alias: fork
      - pkg: github.com/armon/go-metrics/prometheus
        alias: gmprometheus
      - pkg: github.com/mitchellh/go-homedir
        alias: homedir
      - pkg: gitlab.com/unit410/threshold-ed25519/pkg
        alias: tsed25519
      - pkg: github.com/Jille/raft-grpc-transport
        alias: raftgrpctransport
      - pkg: github.com/hashicorp/raft-boltdb/v2
        alias: boltdb
      - pkg: math/rand
        alias: mrand
      - pkg: github.com/consensys/gnark-crypto/ecc/bn254/ecdsa
        alias: ecdsa_bn254
      - pkg: github.com/strangelove-ventures/horcrux/v3/signer/bn254
        alias: horcruxbn254
      - pkg: github.com/strangelove-ventures/horcrux/v3/grpc/cosigner
        alias: grpccosigner
      - pkg: github.com/strangelove-ventures/horcrux/v3/grpc/horcrux
        alias: grpchorcrux
  maligned:
    suggest-new: true
  govet:
    misspell:
      locale: US
run:
  skip-dirs:
    - comet