linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - nolintlint

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  importas:
    no-extra-aliases: true
    alias:
      - pkg: github.com/cosmos/cosmos-sdk/crypto/codec
        alias: cryptocodec
      - pkg: github.com/cosmos/cosmos-sdk/crypto/types
        alias: cryptotypes
      - pkg: github.com/cosmos/cosmos-sdk/x/slashing/types
        alias: slashingtypes
      - pkg: github.com/cometbft/cometbft/types
        alias: tm
      - pkg: github.com/cometbft/cometbft/config
        alias: tmconfig
      - pkg: github.com/cometbft/cometbft/crypto
        alias: tmcrypto
      - pkg: github.com/cometbft/cometbft/crypto/ed25519
        alias: tmcryptoed25519
      - pkg: github.com/cometbft/cometbft/crypto/encoding
        alias: tmcryptoencoding
      - pkg: github.com/tendermint/go-amino
        alias: amino
      - pkg: github.com/cometbft/cometbft/libs/bytes
        alias: tmbytes
      - pkg: github.com/cometbft/cometbft/libs/json
        alias: tmjson
      - pkg: github.com/cometbft/cometbft/libs/log
        alias: tmlog
      - pkg: github.com/cometbft/cometbft/libs/net
        alias: tmnet
      - pkg: github.com/cometbft/cometbft/libs/os
        alias: tmos
      - pkg: github.com/cometbft/cometbft/libs/rand
        alias: tmrand
      - pkg: github.com/cometbft/cometbft/libs/service
        alias: tmservice
      - pkg: github.com/cometbft/cometbft/p2p/conn
        alias: tmp2pconn
      - pkg: github.com/cometbft/cometbft/privval
        alias: tmprivval
      - pkg: github.com/cometbft/cometbft/proto/tendermint/types
        alias: tmproto
      - pkg: github.com/cometbft/cometbft/proto/tendermint/crypto
        alias: tmprotocrypto
      - pkg: github.com/cometbft/cometbft/proto/tendermint/privval
        alias: tmprotoprivval
      - pkg: github.com/cometbft/cometbft/rpc/client
        alias: tmrpcclient
      - pkg: github.com/cometbft/cometbft/rpc/client/http
        alias: tmrpchttp
      - pkg: github.com/cometbft/cometbft/rpc/jsonrpc/client
        alias: tmrpcjsonclient
      - pkg: github.com/cometbft/cometbft/rpc/jsonrpc/types
        alias: tmrpcjsontypes
      - pkg: github.com/cometbft/cometbft/rpc/core/types
        alias: tmrpctypes
      - pkg: github.com/grpc-ecosystem/go-grpc-middleware/retry
        alias: grpcretry
      - pkg: github.com/armon/go-metrics/prometheus
        alias: gmprometheus
      - pkg: github.com/mitchellh/go-homedir
        alias: homedir
      - pkg: gitlab.com/unit410/threshold-ed25519/pkg
        alias: tsed25519
      - pkg: github.com/Jille/raft-grpc-transport
        alias: raftgrpctransport
      - pkg: github.com/hashicorp/raft-boltdb/v2
        alias: boltdb

  maligned:
    suggest-new: true
  govet:
    misspell:
      locale: US
