// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: signer/proto/cosigner_grpc_server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round     int64  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step      int32  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	SignBytes []byte `protobuf:"bytes,4,opt,name=signBytes,proto3" json:"signBytes,omitempty"`
	Timestamp int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Block) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Block) GetSignBytes() []byte {
	if x != nil {
		return x.SignBytes
	}
	return nil
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CosignerGRPCSignBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainID string `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Block   *Block `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *CosignerGRPCSignBlockRequest) Reset() {
	*x = CosignerGRPCSignBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCSignBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCSignBlockRequest) ProtoMessage() {}

func (x *CosignerGRPCSignBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCSignBlockRequest.ProtoReflect.Descriptor instead.
func (*CosignerGRPCSignBlockRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{1}
}

func (x *CosignerGRPCSignBlockRequest) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

func (x *CosignerGRPCSignBlockRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type CosignerGRPCSignBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *CosignerGRPCSignBlockResponse) Reset() {
	*x = CosignerGRPCSignBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCSignBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCSignBlockResponse) ProtoMessage() {}

func (x *CosignerGRPCSignBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCSignBlockResponse.ProtoReflect.Descriptor instead.
func (*CosignerGRPCSignBlockResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{2}
}

func (x *CosignerGRPCSignBlockResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EphemeralSecretPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceID                       int32  `protobuf:"varint,1,opt,name=sourceID,proto3" json:"sourceID,omitempty"`
	DestinationID                  int32  `protobuf:"varint,2,opt,name=destinationID,proto3" json:"destinationID,omitempty"`
	SourceEphemeralSecretPublicKey []byte `protobuf:"bytes,3,opt,name=sourceEphemeralSecretPublicKey,proto3" json:"sourceEphemeralSecretPublicKey,omitempty"`
	EncryptedSharePart             []byte `protobuf:"bytes,4,opt,name=encryptedSharePart,proto3" json:"encryptedSharePart,omitempty"`
	SourceSig                      []byte `protobuf:"bytes,5,opt,name=sourceSig,proto3" json:"sourceSig,omitempty"`
}

func (x *EphemeralSecretPart) Reset() {
	*x = EphemeralSecretPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EphemeralSecretPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemeralSecretPart) ProtoMessage() {}

func (x *EphemeralSecretPart) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemeralSecretPart.ProtoReflect.Descriptor instead.
func (*EphemeralSecretPart) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{3}
}

func (x *EphemeralSecretPart) GetSourceID() int32 {
	if x != nil {
		return x.SourceID
	}
	return 0
}

func (x *EphemeralSecretPart) GetDestinationID() int32 {
	if x != nil {
		return x.DestinationID
	}
	return 0
}

func (x *EphemeralSecretPart) GetSourceEphemeralSecretPublicKey() []byte {
	if x != nil {
		return x.SourceEphemeralSecretPublicKey
	}
	return nil
}

func (x *EphemeralSecretPart) GetEncryptedSharePart() []byte {
	if x != nil {
		return x.EncryptedSharePart
	}
	return nil
}

func (x *EphemeralSecretPart) GetSourceSig() []byte {
	if x != nil {
		return x.SourceSig
	}
	return nil
}

type HRST struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round     int64 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step      int32 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HRST) Reset() {
	*x = HRST{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HRST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HRST) ProtoMessage() {}

func (x *HRST) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HRST.ProtoReflect.Descriptor instead.
func (*HRST) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{4}
}

func (x *HRST) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HRST) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *HRST) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *HRST) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CosignerGRPCSetEphemeralSecretPartsAndSignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedSecrets []*EphemeralSecretPart `protobuf:"bytes,1,rep,name=encryptedSecrets,proto3" json:"encryptedSecrets,omitempty"`
	Hrst             *HRST                  `protobuf:"bytes,2,opt,name=hrst,proto3" json:"hrst,omitempty"`
	SignBytes        []byte                 `protobuf:"bytes,3,opt,name=signBytes,proto3" json:"signBytes,omitempty"`
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) Reset() {
	*x = CosignerGRPCSetEphemeralSecretPartsAndSignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCSetEphemeralSecretPartsAndSignRequest) ProtoMessage() {}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCSetEphemeralSecretPartsAndSignRequest.ProtoReflect.Descriptor instead.
func (*CosignerGRPCSetEphemeralSecretPartsAndSignRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{5}
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) GetEncryptedSecrets() []*EphemeralSecretPart {
	if x != nil {
		return x.EncryptedSecrets
	}
	return nil
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) GetHrst() *HRST {
	if x != nil {
		return x.Hrst
	}
	return nil
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) GetSignBytes() []byte {
	if x != nil {
		return x.SignBytes
	}
	return nil
}

type CosignerGRPCSetEphemeralSecretPartsAndSignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EphemeralPublic []byte `protobuf:"bytes,1,opt,name=ephemeralPublic,proto3" json:"ephemeralPublic,omitempty"`
	Timestamp       int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature       []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignResponse) Reset() {
	*x = CosignerGRPCSetEphemeralSecretPartsAndSignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCSetEphemeralSecretPartsAndSignResponse) ProtoMessage() {}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCSetEphemeralSecretPartsAndSignResponse.ProtoReflect.Descriptor instead.
func (*CosignerGRPCSetEphemeralSecretPartsAndSignResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{6}
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignResponse) GetEphemeralPublic() []byte {
	if x != nil {
		return x.EphemeralPublic
	}
	return nil
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CosignerGRPCSetEphemeralSecretPartsAndSignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CosignerGRPCGetEphemeralSecretPartsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hrst *HRST `protobuf:"bytes,1,opt,name=hrst,proto3" json:"hrst,omitempty"`
}

func (x *CosignerGRPCGetEphemeralSecretPartsRequest) Reset() {
	*x = CosignerGRPCGetEphemeralSecretPartsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCGetEphemeralSecretPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCGetEphemeralSecretPartsRequest) ProtoMessage() {}

func (x *CosignerGRPCGetEphemeralSecretPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCGetEphemeralSecretPartsRequest.ProtoReflect.Descriptor instead.
func (*CosignerGRPCGetEphemeralSecretPartsRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{7}
}

func (x *CosignerGRPCGetEphemeralSecretPartsRequest) GetHrst() *HRST {
	if x != nil {
		return x.Hrst
	}
	return nil
}

type CosignerGRPCGetEphemeralSecretPartsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedSecrets []*EphemeralSecretPart `protobuf:"bytes,1,rep,name=encryptedSecrets,proto3" json:"encryptedSecrets,omitempty"`
}

func (x *CosignerGRPCGetEphemeralSecretPartsResponse) Reset() {
	*x = CosignerGRPCGetEphemeralSecretPartsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCGetEphemeralSecretPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCGetEphemeralSecretPartsResponse) ProtoMessage() {}

func (x *CosignerGRPCGetEphemeralSecretPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCGetEphemeralSecretPartsResponse.ProtoReflect.Descriptor instead.
func (*CosignerGRPCGetEphemeralSecretPartsResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{8}
}

func (x *CosignerGRPCGetEphemeralSecretPartsResponse) GetEncryptedSecrets() []*EphemeralSecretPart {
	if x != nil {
		return x.EncryptedSecrets
	}
	return nil
}

type CosignerGRPCTransferLeadershipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderID string `protobuf:"bytes,1,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
}

func (x *CosignerGRPCTransferLeadershipRequest) Reset() {
	*x = CosignerGRPCTransferLeadershipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCTransferLeadershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCTransferLeadershipRequest) ProtoMessage() {}

func (x *CosignerGRPCTransferLeadershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCTransferLeadershipRequest.ProtoReflect.Descriptor instead.
func (*CosignerGRPCTransferLeadershipRequest) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{9}
}

func (x *CosignerGRPCTransferLeadershipRequest) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

type CosignerGRPCTransferLeadershipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderID      string `protobuf:"bytes,1,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	LeaderAddress string `protobuf:"bytes,2,opt,name=leaderAddress,proto3" json:"leaderAddress,omitempty"`
}

func (x *CosignerGRPCTransferLeadershipResponse) Reset() {
	*x = CosignerGRPCTransferLeadershipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCTransferLeadershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCTransferLeadershipResponse) ProtoMessage() {}

func (x *CosignerGRPCTransferLeadershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signer_proto_cosigner_grpc_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCTransferLeadershipResponse.ProtoReflect.Descriptor instead.
func (*CosignerGRPCTransferLeadershipResponse) Descriptor() ([]byte, []int) {
	return file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP(), []int{10}
}

func (x *CosignerGRPCTransferLeadershipResponse) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *CosignerGRPCTransferLeadershipResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

var File_signer_proto_cosigner_grpc_server_proto protoreflect.FileDescriptor

var file_signer_proto_cosigner_grpc_server_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x85, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5c, 0x0a, 0x1c, 0x43, 0x6f, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x69, 0x67, 0x6e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x44, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x3d, 0x0a, 0x1d, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x69, 0x67, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xed, 0x01, 0x0a, 0x13, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65,
	0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x46, 0x0a, 0x1e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72,
	0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x1e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45,
	0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x12, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x50, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x12, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x50, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x53, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x53, 0x69, 0x67, 0x22, 0x66, 0x0a, 0x04, 0x48, 0x52, 0x53, 0x54, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x74, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xba, 0x01,
	0x0a, 0x31, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65,
	0x74, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x73, 0x41, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x68,
	0x72, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x52, 0x53, 0x54, 0x52, 0x04, 0x68, 0x72, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x32, 0x43,
	0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65, 0x74, 0x45, 0x70,
	0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x74, 0x73, 0x41, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x65, 0x70, 0x68, 0x65,
	0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x4d, 0x0a, 0x2a, 0x43, 0x6f, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x74, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65,
	0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x68, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x52, 0x53, 0x54,
	0x52, 0x04, 0x68, 0x72, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x2b, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x74, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72,
	0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x10, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x22, 0x43, 0x0a,
	0x25, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x49, 0x44, 0x22, 0x6a, 0x0a, 0x26, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52,
	0x50, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0xfc,
	0x03, 0x0a, 0x0c, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x12,
	0x58, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50,
	0x43, 0x53, 0x69, 0x67, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x69, 0x67, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x97, 0x01, 0x0a, 0x1e, 0x53, 0x65,
	0x74, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x73, 0x41, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x38, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50,
	0x43, 0x53, 0x65, 0x74, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x41, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65, 0x74, 0x45, 0x70,
	0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x74, 0x73, 0x41, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x82, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x45, 0x70, 0x68, 0x65, 0x6d,
	0x65, 0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x12,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x74, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x74, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65,
	0x72, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x2c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47,
	0x52, 0x50, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50,
	0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x6c, 0x6f, 0x76, 0x65, 0x2d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2f, 0x68, 0x6f, 0x72, 0x63, 0x72, 0x75, 0x78, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_signer_proto_cosigner_grpc_server_proto_rawDescOnce sync.Once
	file_signer_proto_cosigner_grpc_server_proto_rawDescData = file_signer_proto_cosigner_grpc_server_proto_rawDesc
)

func file_signer_proto_cosigner_grpc_server_proto_rawDescGZIP() []byte {
	file_signer_proto_cosigner_grpc_server_proto_rawDescOnce.Do(func() {
		file_signer_proto_cosigner_grpc_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_signer_proto_cosigner_grpc_server_proto_rawDescData)
	})
	return file_signer_proto_cosigner_grpc_server_proto_rawDescData
}

var file_signer_proto_cosigner_grpc_server_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_signer_proto_cosigner_grpc_server_proto_goTypes = []interface{}{
	(*Block)(nil),                         // 0: proto.Block
	(*CosignerGRPCSignBlockRequest)(nil),  // 1: proto.CosignerGRPCSignBlockRequest
	(*CosignerGRPCSignBlockResponse)(nil), // 2: proto.CosignerGRPCSignBlockResponse
	(*EphemeralSecretPart)(nil),           // 3: proto.EphemeralSecretPart
	(*HRST)(nil),                          // 4: proto.HRST
	(*CosignerGRPCSetEphemeralSecretPartsAndSignRequest)(nil),  // 5: proto.CosignerGRPCSetEphemeralSecretPartsAndSignRequest
	(*CosignerGRPCSetEphemeralSecretPartsAndSignResponse)(nil), // 6: proto.CosignerGRPCSetEphemeralSecretPartsAndSignResponse
	(*CosignerGRPCGetEphemeralSecretPartsRequest)(nil),         // 7: proto.CosignerGRPCGetEphemeralSecretPartsRequest
	(*CosignerGRPCGetEphemeralSecretPartsResponse)(nil),        // 8: proto.CosignerGRPCGetEphemeralSecretPartsResponse
	(*CosignerGRPCTransferLeadershipRequest)(nil),              // 9: proto.CosignerGRPCTransferLeadershipRequest
	(*CosignerGRPCTransferLeadershipResponse)(nil),             // 10: proto.CosignerGRPCTransferLeadershipResponse
}
var file_signer_proto_cosigner_grpc_server_proto_depIdxs = []int32{
	0,  // 0: proto.CosignerGRPCSignBlockRequest.block:type_name -> proto.Block
	3,  // 1: proto.CosignerGRPCSetEphemeralSecretPartsAndSignRequest.encryptedSecrets:type_name -> proto.EphemeralSecretPart
	4,  // 2: proto.CosignerGRPCSetEphemeralSecretPartsAndSignRequest.hrst:type_name -> proto.HRST
	4,  // 3: proto.CosignerGRPCGetEphemeralSecretPartsRequest.hrst:type_name -> proto.HRST
	3,  // 4: proto.CosignerGRPCGetEphemeralSecretPartsResponse.encryptedSecrets:type_name -> proto.EphemeralSecretPart
	1,  // 5: proto.CosignerGRPC.SignBlock:input_type -> proto.CosignerGRPCSignBlockRequest
	5,  // 6: proto.CosignerGRPC.SetEphemeralSecretPartsAndSign:input_type -> proto.CosignerGRPCSetEphemeralSecretPartsAndSignRequest
	7,  // 7: proto.CosignerGRPC.GetEphemeralSecretParts:input_type -> proto.CosignerGRPCGetEphemeralSecretPartsRequest
	9,  // 8: proto.CosignerGRPC.TransferLeadership:input_type -> proto.CosignerGRPCTransferLeadershipRequest
	2,  // 9: proto.CosignerGRPC.SignBlock:output_type -> proto.CosignerGRPCSignBlockResponse
	6,  // 10: proto.CosignerGRPC.SetEphemeralSecretPartsAndSign:output_type -> proto.CosignerGRPCSetEphemeralSecretPartsAndSignResponse
	8,  // 11: proto.CosignerGRPC.GetEphemeralSecretParts:output_type -> proto.CosignerGRPCGetEphemeralSecretPartsResponse
	10, // 12: proto.CosignerGRPC.TransferLeadership:output_type -> proto.CosignerGRPCTransferLeadershipResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_signer_proto_cosigner_grpc_server_proto_init() }
func file_signer_proto_cosigner_grpc_server_proto_init() {
	if File_signer_proto_cosigner_grpc_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCSignBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCSignBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EphemeralSecretPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HRST); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCSetEphemeralSecretPartsAndSignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCSetEphemeralSecretPartsAndSignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCGetEphemeralSecretPartsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCGetEphemeralSecretPartsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCTransferLeadershipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signer_proto_cosigner_grpc_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCTransferLeadershipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signer_proto_cosigner_grpc_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signer_proto_cosigner_grpc_server_proto_goTypes,
		DependencyIndexes: file_signer_proto_cosigner_grpc_server_proto_depIdxs,
		MessageInfos:      file_signer_proto_cosigner_grpc_server_proto_msgTypes,
	}.Build()
	File_signer_proto_cosigner_grpc_server_proto = out.File
	file_signer_proto_cosigner_grpc_server_proto_rawDesc = nil
	file_signer_proto_cosigner_grpc_server_proto_goTypes = nil
	file_signer_proto_cosigner_grpc_server_proto_depIdxs = nil
}
