name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened and what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Describe how to reproduce the bug
      placeholder: Step by step method to recreate the issue.
    validations:
      required: true
  - type: input
    id: Version
    attributes:
      label: version
      description: What version of the software are you using?
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or stack trace
      description: Please copy and paste any relevant output from the code. This will be automatically formatted so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../../CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
