/*
Package types: Nonce.go contains the types for nonce and nonces
*/
package types

import "time"

// Nonces contains the ephemeral information generated by one cosigner (local) for all other cosigners (remote).
type Nonces struct {
	PubKey []byte
	Shares [][]byte
}

type NoncesWithExpiration struct {
	Expiration time.Time
	Nonces     []Nonces
}

// Nonce is the ephemeral information from another cosigner (remote) destined for this cosigner (local).
type Nonce struct {
	Index  int
	Share  []byte
	PubKey []byte
}

// PartialSignature contains the signature and identifier for a piece of the combined signature.
type PartialSignature struct {
	Index     int
	Signature []byte
}
