mode = "mpc"
key_file = "/Users/johnzampolin/go/src/github.com/strangelove-ventures/horcrux/data/signer3/priv-key-shard.json"
state_dir = "/Users/johnzampolin/go/src/github.com/strangelove-ventures/horcrux/data/signer3/"
chain_id = "test-chain-id"
cosigner_threshold = 2
cosigner_listen_address = "tcp://0.0.0.0:2224"

[[cosigner]]
id = 1
remote_address = "tcp://0.0.0.0:2222"

[[cosigner]]
id = 2
remote_address = "tcp://0.0.0.0:2223"
