// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.13.0
// source: cosigner_grpc_server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ICosignerGRPCServer_SignBlock_FullMethodName          = "/proto.ICosignerGRPCServer/SignBlock"
	ICosignerGRPCServer_SetNoncesAndSign_FullMethodName   = "/proto.ICosignerGRPCServer/SetNoncesAndSign"
	ICosignerGRPCServer_GetNonces_FullMethodName          = "/proto.ICosignerGRPCServer/GetNonces"
	ICosignerGRPCServer_TransferLeadership_FullMethodName = "/proto.ICosignerGRPCServer/TransferLeadership"
	ICosignerGRPCServer_GetLeader_FullMethodName          = "/proto.ICosignerGRPCServer/GetLeader"
)

// ICosignerGRPCServerClient is the client API for ICosignerGRPCServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ICosignerGRPCServerClient interface {
	SignBlock(ctx context.Context, in *CosignerGRPCSignBlockRequest, opts ...grpc.CallOption) (*CosignerGRPCSignBlockResponse, error)
	SetNoncesAndSign(ctx context.Context, in *CosignerGRPCSetNoncesAndSignRequest, opts ...grpc.CallOption) (*CosignerGRPCSetNoncesAndSignResponse, error)
	GetNonces(ctx context.Context, in *CosignerGRPCGetNoncesRequest, opts ...grpc.CallOption) (*CosignerGRPCGetNoncesResponse, error)
	TransferLeadership(ctx context.Context, in *CosignerGRPCTransferLeadershipRequest, opts ...grpc.CallOption) (*CosignerGRPCTransferLeadershipResponse, error)
	GetLeader(ctx context.Context, in *CosignerGRPCGetLeaderRequest, opts ...grpc.CallOption) (*CosignerGRPCGetLeaderResponse, error)
}

type iCosignerGRPCServerClient struct {
	cc grpc.ClientConnInterface
}

func NewICosignerGRPCServerClient(cc grpc.ClientConnInterface) ICosignerGRPCServerClient {
	return &iCosignerGRPCServerClient{cc}
}

func (c *iCosignerGRPCServerClient) SignBlock(ctx context.Context, in *CosignerGRPCSignBlockRequest, opts ...grpc.CallOption) (*CosignerGRPCSignBlockResponse, error) {
	out := new(CosignerGRPCSignBlockResponse)
	err := c.cc.Invoke(ctx, ICosignerGRPCServer_SignBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCosignerGRPCServerClient) SetNoncesAndSign(ctx context.Context, in *CosignerGRPCSetNoncesAndSignRequest, opts ...grpc.CallOption) (*CosignerGRPCSetNoncesAndSignResponse, error) {
	out := new(CosignerGRPCSetNoncesAndSignResponse)
	err := c.cc.Invoke(ctx, ICosignerGRPCServer_SetNoncesAndSign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCosignerGRPCServerClient) GetNonces(ctx context.Context, in *CosignerGRPCGetNoncesRequest, opts ...grpc.CallOption) (*CosignerGRPCGetNoncesResponse, error) {
	out := new(CosignerGRPCGetNoncesResponse)
	err := c.cc.Invoke(ctx, ICosignerGRPCServer_GetNonces_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCosignerGRPCServerClient) TransferLeadership(ctx context.Context, in *CosignerGRPCTransferLeadershipRequest, opts ...grpc.CallOption) (*CosignerGRPCTransferLeadershipResponse, error) {
	out := new(CosignerGRPCTransferLeadershipResponse)
	err := c.cc.Invoke(ctx, ICosignerGRPCServer_TransferLeadership_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCosignerGRPCServerClient) GetLeader(ctx context.Context, in *CosignerGRPCGetLeaderRequest, opts ...grpc.CallOption) (*CosignerGRPCGetLeaderResponse, error) {
	out := new(CosignerGRPCGetLeaderResponse)
	err := c.cc.Invoke(ctx, ICosignerGRPCServer_GetLeader_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ICosignerGRPCServerServer is the server API for ICosignerGRPCServer service.
// All implementations must embed UnimplementedICosignerGRPCServerServer
// for forward compatibility
type ICosignerGRPCServerServer interface {
	SignBlock(context.Context, *CosignerGRPCSignBlockRequest) (*CosignerGRPCSignBlockResponse, error)
	SetNoncesAndSign(context.Context, *CosignerGRPCSetNoncesAndSignRequest) (*CosignerGRPCSetNoncesAndSignResponse, error)
	GetNonces(context.Context, *CosignerGRPCGetNoncesRequest) (*CosignerGRPCGetNoncesResponse, error)
	TransferLeadership(context.Context, *CosignerGRPCTransferLeadershipRequest) (*CosignerGRPCTransferLeadershipResponse, error)
	GetLeader(context.Context, *CosignerGRPCGetLeaderRequest) (*CosignerGRPCGetLeaderResponse, error)
	mustEmbedUnimplementedICosignerGRPCServerServer()
}

// UnimplementedICosignerGRPCServerServer must be embedded to have forward compatible implementations.
type UnimplementedICosignerGRPCServerServer struct {
}

func (UnimplementedICosignerGRPCServerServer) SignBlock(context.Context, *CosignerGRPCSignBlockRequest) (*CosignerGRPCSignBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBlock not implemented")
}
func (UnimplementedICosignerGRPCServerServer) SetNoncesAndSign(context.Context, *CosignerGRPCSetNoncesAndSignRequest) (*CosignerGRPCSetNoncesAndSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNoncesAndSign not implemented")
}
func (UnimplementedICosignerGRPCServerServer) GetNonces(context.Context, *CosignerGRPCGetNoncesRequest) (*CosignerGRPCGetNoncesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNonces not implemented")
}
func (UnimplementedICosignerGRPCServerServer) TransferLeadership(context.Context, *CosignerGRPCTransferLeadershipRequest) (*CosignerGRPCTransferLeadershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferLeadership not implemented")
}
func (UnimplementedICosignerGRPCServerServer) GetLeader(context.Context, *CosignerGRPCGetLeaderRequest) (*CosignerGRPCGetLeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedICosignerGRPCServerServer) mustEmbedUnimplementedICosignerGRPCServerServer() {}

// UnsafeICosignerGRPCServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ICosignerGRPCServerServer will
// result in compilation errors.
type UnsafeICosignerGRPCServerServer interface {
	mustEmbedUnimplementedICosignerGRPCServerServer()
}

func RegisterICosignerGRPCServerServer(s grpc.ServiceRegistrar, srv ICosignerGRPCServerServer) {
	s.RegisterService(&ICosignerGRPCServer_ServiceDesc, srv)
}

func _ICosignerGRPCServer_SignBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCSignBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICosignerGRPCServerServer).SignBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ICosignerGRPCServer_SignBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICosignerGRPCServerServer).SignBlock(ctx, req.(*CosignerGRPCSignBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICosignerGRPCServer_SetNoncesAndSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCSetNoncesAndSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICosignerGRPCServerServer).SetNoncesAndSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ICosignerGRPCServer_SetNoncesAndSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICosignerGRPCServerServer).SetNoncesAndSign(ctx, req.(*CosignerGRPCSetNoncesAndSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICosignerGRPCServer_GetNonces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCGetNoncesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICosignerGRPCServerServer).GetNonces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ICosignerGRPCServer_GetNonces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICosignerGRPCServerServer).GetNonces(ctx, req.(*CosignerGRPCGetNoncesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICosignerGRPCServer_TransferLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCTransferLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICosignerGRPCServerServer).TransferLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ICosignerGRPCServer_TransferLeadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICosignerGRPCServerServer).TransferLeadership(ctx, req.(*CosignerGRPCTransferLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICosignerGRPCServer_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCGetLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICosignerGRPCServerServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ICosignerGRPCServer_GetLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICosignerGRPCServerServer).GetLeader(ctx, req.(*CosignerGRPCGetLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ICosignerGRPCServer_ServiceDesc is the grpc.ServiceDesc for ICosignerGRPCServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ICosignerGRPCServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ICosignerGRPCServer",
	HandlerType: (*ICosignerGRPCServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignBlock",
			Handler:    _ICosignerGRPCServer_SignBlock_Handler,
		},
		{
			MethodName: "SetNoncesAndSign",
			Handler:    _ICosignerGRPCServer_SetNoncesAndSign_Handler,
		},
		{
			MethodName: "GetNonces",
			Handler:    _ICosignerGRPCServer_GetNonces_Handler,
		},
		{
			MethodName: "TransferLeadership",
			Handler:    _ICosignerGRPCServer_TransferLeadership_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _ICosignerGRPCServer_GetLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosigner_grpc_server.proto",
}
