name: "Release"

on:
  push:
    branches: 
      - "RC[0-9]/**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      # TODO:figure out how to add the supported SDK and tendermint versions
      # here we need to run the following and save the results to ENV in the goreleaser action
      # SDKVERSION := $(shell go list -m -u -f '{{.Version}}' github.com/cosmos/cosmos-sdk)
      # TMVERSION := $(shell go list -m -u -f '{{.Version}}' github.com/tendermint/tendermint)
      # Also see .goreleaser.yaml to wire up the environment variables

      # Once this is solved we should also be able to use https://github.com/pmorelli92/github-container-registry-build-push
      # to build the right simd version and push it to githubs docker repo

      - run: echo ":rocket::rocket::rocket:" > ../release_notes.md 
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --skip-validate   # skip validate skips initial sanity checks in order to be able to fully run

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist --release-notes=../release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}